// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Assignment_WEBAPI_D2.Models;

[Table("TestTable")]
public partial class TestTable
{
    [Key]
    public int StudentID { get; set; }

    public int CourseID { get; set; }

    public int Grade { get; set; }
}